import { IndexType } from './IndexType';
import { NodeLabel } from '../node/NodeLabel';
import { AbstractIndex } from './AbstractIndex';

export class BtreeIndex extends AbstractIndex {
  getIndexType(): IndexType {
    return 'btree';
  }

  protected getAutogeneratedName(): string {
    const keys = this.on.sort().join('_');

    return `SPNL_i_${
      this.labelOrType instanceof NodeLabel ? 'n' : 'r'
    }_bt_${this.labelOrType.toString()}_${keys}`;
  }
}
