import { IndexType } from './IndexType';
import { NodeLabel } from '../node/NodeLabel';
import { AbstractIndex } from './AbstractIndex';

export class FullTextIndex extends AbstractIndex {
  getIndexType(): IndexType {
    return 'fulltext';
  }

  protected getAutogeneratedName() {
    const keys = this.on.sort().join('_');

    return `SPNL_i_${
      this.labelOrType instanceof NodeLabel ? 'n' : 'r'
    }_ft_${this.labelOrType.toString()}_${keys}`;
  }
}
