name: Take coverage
on: [ push ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: comment
          test-script: npm run test:unit
        env:
          HUSKY: 0
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
