name: Run test
on: [ push ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    services:
      neo4j:
        image: neo4j:5.3-enterprise
        ports:
          - 7687:7687
        env:
          NEO4J_URI: "bolt://localhost:7687"
          NEO4J_USERNAME: "neo4j"
          NEO4J_PASSWORD: "neo4j"
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
        options: >-
          --health-cmd "cypher-shell 'match (n) return count(n)'"
          --health-timeout 10s
          --health-retries 20
          --health-interval 10s
          --health-start-period 30s
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: run test
        run: npm run test:integration

